export {default as UserPagesIndex} from './UserPagesIndex'
export {default as WelcomeTextArea} from './WelcomeTextArea'
export {default as PagesIndex} from './PagesIndex'
export {default as ProfileItemsArea} from './ProfileItemsArea'
export {default as UserPagesTabs} from './UserPagesTabs'
export {default as ProfileItems} from './ProfileItems'