export {default as Input} from './Input'
export {default as Form} from './Form'
export {default as RegisterForm} from './RegisterForm'
export {default as LoginForm} from './LoginForm'
export {default as ResetPasswordForm} from './ResetPasswordForm'
export {default as ResetPasswordConfirmForm} from './ResetPasswordConfirmForm'

export {default as ModalForm} from './modelForm/ModalForm'
export {default as CheckEmailModalForm} from './modelForm/CheckEmailModalForm'
export {default as RegistrationModalForm} from './modelForm/RegistrationModalForm'
export {default as AddDetailsModalForm} from './modelForm/AddDetailsModalForm'
export {default as LoginModalForm} from './modelForm/LoginModalForm'
export {default as ProfessorSignUpModalForm} from './modelForm/ProfessorSignUpModalForm'
